export const tagCategories = [
  {
    id: "material",
    label: "Material",
    tags: [
      "air",
      "cloth",
      "cleanconcrete",
      "concrete",
      "bricks",
      "cardboard",
      "carpet",
      "debris",
      "dirt",
      "fabric",
      "floor",
      "glass",
      "gravel",
      "ice",
      "leather",
      "leaves",
      "liquid",
      "materials",
      "metal",
      "metallic",
      "metlmisc",
      "mud",
      "paper",
      "plastic",
      "rock",
      "rocks",
      "sand",
      "solidwood",
      "stone",
      "tile",
      "water",
      "wet",
      "wood",
      "wooden",
    ],
  },
  {
    id: "content",
    label: "Content",
    tags: [
      "airblow",
      "ambience",
      "atmosphere",
      "bass drop",
      "blast",
      "drone",
      "drop",
      "elecarc",
      "electric",
      "electromagnetic",
      "electronic",
      "electricity",
      "energy",
      "effects",
      "efx",
      "elements",
      "element",
      "foley",
      "game",
      "glitch",
      "impact",
      "impacts",
      "creak",
      "machine",
      "machines",
      "machina",
      "magic",
      "mechanical",
      "noise",
      "physics",
      "power",
      "riser",
      "risers",
      "sonic",
      "soundbits",
      "soundeffects",
      "spark",
      "spray",
      "transition",
      "digital",
      "drones",
      "elecemf",
      "ringing",
      "whoosh",
      "whsh",
    ],
  },
  {
    id: "ui",
    label: "UI",
    tags: [
      "button",
      "buttons",
      "cmptkey",
      "exit",
      "interface",
      "optionsmenus",
      "press",
      "select",
      "switch",
      "uialert",
      "uiclick",
      "uimvmt",
      "ui",
      "user",
    ],
  },
  {
    id: "form",
    label: "Form",
    tags: ["double", "group", "loop", "mono", "one shot", "single", "stereo"],
  },
  {
    id: "object",
    label: "Object",
    tags: [
      "bar",
      "bell",
      "bin",
      "board",
      "box",
      "bottle",
      "cabinet",
      "can",
      "canister",
      "chair",
      "chain",
      "computer",
      "computers",
      "cutlery",
      "door",
      "doors",
      "doormetl",
      "doorslid",
      "doorwood",
      "drawer",
      "drawers",
      "food",
      "foodtware",
      "furniture",
      "key",
      "keyboard",
      "latch",
      "laundry",
      "lid",
      "lock",
      "object",
      "objects",
      "objfurn",
      "objwrite",
      "plate",
      "pole",
      "rack",
      "ramps",
      "roller",
      "saw",
      "screwdriver",
      "sheet",
      "springs",
      "spring",
      "table",
      "tableware",
      "tools",
      "window",
      "zapper",
    ],
  },
  {
    id: "environment",
    label: "Environment",
    tags: [
      "amb",
      "ambient",
      "ambiences",
      "bathroom",
      "church",
      "city",
      "crowd",
      "exterior",
      "ext",
      "factory",
      "forest",
      "house",
      "indoor",
      "industrial",
      "industry",
      "inside",
      "interior",
      "int",
      "levels",
      "canals",
      "marine",
      "maze",
      "nature",
      "night",
      "office",
      "outdoor",
      "outside",
      "place",
      "prison",
      "rain",
      "road",
      "stairs",
      "room",
      "space",
      "stage",
      "thunder",
      "traffic",
      "urban",
      "weather",
      "wind",
    ],
  },
  {
    id: "creature",
    label: "Creature",
    tags: [
      "animal",
      "animals",
      "alien",
      "antlion",
      "bat",
      "bird",
      "birds",
      "boss",
      "cat",
      "creature",
      "dog",
      "feetanml",
      "gore",
      "headcrab",
      "monster",
    ],
  },
  {
    id: "subject",
    label: "Subject",
    tags: [
      "character",
      "combine",
      "combine soldier",
      "female",
      "human",
      "male",
      "metropolice",
      "npc",
      "overwatch",
      "player",
      "robot",
      "security",
      "soldier",
      "zombie",
    ],
  },
  {
    id: "body",
    label: "Body",
    tags: ["barefoot", "flesh", "fvox", "hand", "head", "skin"],
  },
  {
    id: "voice",
    label: "VO",
    tags: [
      "dialogue",
      "call",
      "chinese",
      "you",
      "ivo",
      "radio",
      "radiovoice",
      "speech",
      "vo",
      "voice",
      "voices",
      "vocal",
    ],
  },
  {
    id: "action",
    label: "Action",
    tags: [
      "action",
      "alert",
      "approach",
      "applause",
      "articulated",
      "attack",
      "away",
      "battle",
      "click",
      "close",
      "crash",
      "cut",
      "death",
      "down",
      "drive",
      "driving",
      "hit",
      "hits",
      "idle",
      "jump",
      "lands",
      "move",
      "moves",
      "open",
      "patting",
      "pickup",
      "pick",
      "pull",
      "push",
      "rattle",
      "release",
      "remove",
      "run",
      "running",
      "shaking",
      "shut",
      "slam",
      "shot",
      "shots",
      "slide",
      "slides",
      "sliding",
      "start",
      "stop",
      "stops",
      "turn",
      "turns",
      "walk",
      "writing",
      "tear",
    ],
  },
  {
    id: "weapon",
    label: "Weapon",
    tags: ["bullet", "firearm", "melee", "shot", "weapon", "weapons"],
  },
  {
    id: "weapon-gun",
    label: "Gun",
    parentId: "weapon",
    tags: ["gun"],
  },
  {
    id: "weapon-gun-smg",
    label: "Submachine Gun",
    parentId: "weapon-gun",
    tags: ["submachine gun", "machine gun", "smg", "mp5", "mac 10", "thompson"],
  },
  {
    id: "weapon-gun-rifle",
    label: "Rifle",
    parentId: "weapon-gun",
    tags: ["rifle", "browning", "hk53", "winchester"],
  },
  {
    id: "weapon-gun-handgun",
    label: "Handgun",
    parentId: "weapon-gun",
    tags: ["handgun", "pistol", "glock", "colt", "magnum", "smith wesson"],
  },
  {
    id: "weapon-gun-shotgun",
    label: "Shotgun",
    parentId: "weapon-gun",
    tags: ["shotgun", "shot gun", "12 gauge"],
  },
  {
    id: "vehicle",
    label: "Vehicle",
    tags: [
      "aircraft",
      "airplane",
      "accord",
      "auto",
      "boat",
      "car",
      "civic",
      "civicex",
      "cutlass",
      "engine",
      "escort",
      "exhaust",
      "ford",
      "ford-f",
      "gas",
      "helicopter",
      "honda",
      "horn",
      "jet",
      "lincoln",
      "motor",
      "motorcycle",
      "oldsmobile",
      "onboard",
      "pedal",
      "race",
      "rpm",
      "ship",
      "subarucrosstrek",
      "suv",
      "tank",
      "train",
      "truck",
      "vehicle",
      "vehicles",
    ],
  },
  {
    id: "music",
    label: "Music",
    tags: [
      "bass",
      "braam",
      "breathofthewildpiano",
      "cyberpunk",
      "dnb",
      "drum",
      "drums",
      "edm",
      "houseedm",
      "intro",
      "introthemes",
      "levelthemes",
      "lofi",
      "modernpiano",
      "music",
      "orchestral",
      "percussion",
      "pop",
      "pulse",
      "rpgthemes",
      "stinger",
      "synth",
      "synthambiences",
      "synthwave",
      "techno",
      "themes",
      "trance",
      "trap",
    ],
  },
  {
    id: "motion",
    label: "Motion",
    tags: [
      "airborne",
      "boots",
      "fast",
      "fly",
      "footstep",
      "footsteps",
      "foleyfeet",
      "flow",
      "friction",
      "left",
      "medium",
      "mid",
      "metlfric",
      "metlmvmt",
      "moving",
      "movement",
      "pass",
      "passby",
      "quick",
      "back",
      "rear",
      "reverse",
      "right",
      "roll",
      "rubbing",
      "scrape",
      "scuffs",
      "shoes",
      "side",
      "slow",
      "sneakers",
      "speed",
      "step",
      "stroke",
      "swipe",
    ],
  },
  {
    id: "tone",
    label: "Tone",
    tags: [
      "aggressive",
      "airy",
      "atonal",
      "big",
      "cinematic",
      "clean",
      "dark",
      "deep",
      "designed",
      "design",
      "distant",
      "dramatic",
      "dry",
      "eerie",
      "empty",
      "full",
      "future",
      "futuristic",
      "hard",
      "harsh",
      "heavy",
      "high",
      "horror",
      "large",
      "light",
      "long",
      "low",
      "old",
      "quirky",
      "retro",
      "scary",
      "sci",
      "sci-fi",
      "scifi",
      "short",
      "small",
      "soft",
      "solid",
      "steady",
      "tech",
      "tonal",
      "tone",
      "trailer",
      "production",
      "sfx",
      "compressed",
    ],
  },
  {
    id: "destruction",
    label: "Destruction",
    tags: [
      "blast",
      "boom",
      "break",
      "broken",
      "burst",
      "explo",
      "explosion",
      "explosions",
      "fire",
      "poison",
      "rumble",
    ],
  },
  {
    id: "recording",
    label: "Recording",
    tags: [
      "ambisonics",
      "dpa",
      "layer",
      "mkh",
      "mix",
      "multiple",
      "onboard",
      "ortf",
      "rsm",
      "take",
      "tape",
      "texture",
      "textures",
      "track",
      "vol",
      "waves",
    ],
  },
  {
    id: "source",
    label: "Source",
    tags: [
      "anderson",
      "bluezone",
      "bluezonecorp",
      "construction",
      "david",
      "dsgnrise",
      "dsgnstngr",
      "dumais",
      "eiravaein",
      "federico",
      "fienup",
      "inmotionaudio",
      "inspectorj",
      "jse",
      "justsoundeffects",
      "krotos",
      "matiasmacsd",
      "mchugh",
      "metlimpt",
      "onbrd",
      "pmsfx",
      "rdgsfx",
      "soler",
      "soundholder",
      "soundmorph",
      "soundopolis",
      "theworkroom",
      "timothy",
      "toolpowr",
      "various",
      "vicic",
      "watsonwu",
    ],
  },
  {
    id: "technical",
    label: "Technical",
    tags: [
      "bit",
      "coll",
      "external",
      "front",
      "from",
      "general",
      "internal",
      "into",
      "llc",
      "misc",
      "off",
      "out",
      "position",
      "post",
      "source",
      "that",
      "this",
      "through",
      "time",
      "two",
      "var",
      "very",
      "with",
      "decoded",
      "works",
    ],
  },
];

type TagCategory = (typeof tagCategories)[number];
type TagCategoryRef = { id: string; label: string; parentId?: string };

const ignoredTags = new Set<string>();
const tagToCategory = new Map(
  tagCategories.flatMap((category) =>
    category.tags.map((tag) => [tag, category] as const),
  ),
);
const maxKeywordSummaryTags = 8;

export function isIgnoredTag(tag: string): boolean {
  return ignoredTags.has(canonicalizeTag(tag));
}

export function tagCategoryForTag(tag: string): TagCategoryRef {
  const normalized = canonicalizeTag(tag);
  const category = tagToCategory.get(normalized);
  return category
    ? { id: category.id, label: category.label, parentId: category.parentId }
    : { id: "keyword", label: "Keywords" };
}

export function tagCategoryPathForTag(tag: string): TagCategoryRef[] {
  const category = tagCategoryForTag(tag);
  if (category.id === "keyword") return [category];

  const path: TagCategoryRef[] = [];
  let current: TagCategory | undefined = tagCategories.find(
    (candidate) => candidate.id === category.id,
  );
  while (current) {
    path.unshift({
      id: current.id,
      label: current.label,
      parentId: current.parentId,
    });
    current = current.parentId
      ? tagCategories.find((candidate) => candidate.id === current?.parentId)
      : undefined;
  }
  return path;
}

export function categorySummaryForTags(tags: string[]): string {
  const grouped = new Map<string, { label: string; tags: string[] }>();
  const keywords: string[] = [];

  for (const tag of tags) {
    const normalized = canonicalizeTag(tag);
    if (!normalized || isIgnoredTag(normalized)) continue;
    const category = tagToCategory.get(normalized);
    if (!category) {
      if (normalized && !keywords.includes(normalized)) keywords.push(normalized);
      continue;
    }

    const existing = grouped.get(category.id) ?? {
      label: category.label,
      tags: [],
    };
    if (!existing.tags.includes(normalized)) existing.tags.push(normalized);
    grouped.set(category.id, existing);
  }

  if (keywords.length > 0) {
    grouped.set("keyword", {
      label: "Keywords",
      tags:
        keywords.length > maxKeywordSummaryTags
          ? [
              ...keywords.slice(0, maxKeywordSummaryTags),
              `+${keywords.length - maxKeywordSummaryTags}`,
            ]
          : keywords,
    });
  }

  return [...grouped.values()]
    .map((group) => `${group.label}: ${group.tags.join(", ")}`)
    .join(" | ");
}

export function canonicalizeTag(tag: string): string {
  return tag
    .trim()
    .toLowerCase()
    .replace(/_/g, " ")
    .replace(/[^a-z0-9\-\s]+/g, " ")
    .replace(/\s+/g, " ")
    .replace(/^-+|-+$/g, "")
    .trim();
}
